---
# tasks/main.yml

- name: Configure sudoers file
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/custom_sudoers
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'
